<?php

namespace JCLE\MemoBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends EntityRepository
{   
    public function recherche ( $recherche, $username, $page, $maxParPage )
    {
            $qb = $this->_em->createQueryBuilder();
            $qb->select('n')
            ->from('JCLEMemoBundle:Note', 'n');
          
            $qb = $this->requeteDeRecherche($recherche, $username, $qb);
            
//            $qb->setFirstResult(($page-1)* $maxParPage)
//                ->setMaxResults($maxParPage);
        
        return new Paginator($qb);
    }
    
    public function countRecherche ( $recherche, $username )
    {
            $qb = $this->_em->createQueryBuilder();
           $qb->select('COUNT (n.id)')
            ->from('JCLEMemoBundle:Note', 'n');
           
           $qb = $this->requeteDeRecherche($recherche, $username, $qb);
        
        return $qb->getQuery()->getSingleScalarResult();
    }
    
    public function requeteDeRecherche ($recherche, $username, $qb)
    {
        foreach ($recherche as $key => $value )
            {
                if($key == 0)
                { $qb->where($qb->expr()->like('n.titre', ':recherche'.$key)); }
                else
                { $qb->andWhere($qb->expr()->like('n.titre', ':recherche'.$key)); }
                
                $qb->orWhere($qb->expr()->like('n.tag', ':recherche'.$key))
                   ->orWhere($qb->expr()->like('n.description', ':recherche'.$key))
                    ->setParameter('recherche'.$key, '%'.$recherche[$key].'%' );
                // la key me sers à identifier le mot a substituer ex :     :recherche1 va recevoir la valeur du 1er element et ainsi de suite
            }
            $qb->andWhere('n.createur = :username')
            ->setParameter('username', $username );
            return $qb;
    }
    
    /**
     * Rechercher les icones comprenant des notes pour un utilisateur spécifié
     * @param type $user
     * @return array
     */
    public function findIconsHaveNotes($user)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('DISTINCT i.alt, i.id')
            ->from('JCLEMemoBundle:Note', 'n')
            ->Join('n.icon','i')
            ->where('n.createur = :username')
            ->setParameter('username', $user );
        
        return $qb->getQuery()
                ->getArrayResult();
    }
    
    /**
     * Rechercher toutes les icones d'un utilisateur spécifié
     * @param type $user
     * @return array
     */
    public function findIconsFromUser($user)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('DISTINCT i')
            ->from('JCLEMemoBundle:Icon', 'i')
            ->where('i.createur = :username')
            ->setParameter('username', $user );
        
        return $qb->getQuery()
                ->getArrayResult();
    }
    
    public function findByIcon($iconAlt, $username, $page, $maxParPage)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('n, n.id, n.titre, n.date, n.slug, u.username')
                ->from('JCLEMemoBundle:Note', 'n')
                    ->Join('n.icon','i')
                    ->Join('n.createur','u')
                    ->where('i.alt = :altIcon')
                    ->setParameter('altIcon', $iconAlt )
                    ->andWhere('u.username = :username')           
                    ->setParameter('username', $username );
        
//        $qb->setFirstResult(($page-1)* $maxParPage)
//                ->setMaxResults($maxParPage);
        
//        return new Paginator($qb);
        return $qb->getQuery()->getArrayResult();
    }
    
    public function countIcon ($iconAlt, $username)
    {
        $qb= $this->createQueryBuilder('id')
            ->select('COUNT(DISTINCT n.id)')
                ->from('JCLEMemoBundle:Note', 'n')
                    ->Join('n.icon','i')
                    ->Join('n.createur','u')
                    ->where('i.alt = :altIcon')
                    ->setParameter('altIcon', $iconAlt )
                    ->andWhere('u.username = :username')           
                    ->setParameter('username', $username );

        return $qb->getQuery()
                  ->getSingleScalarResult();  
    }
    
    public function requeteDeIcon ($iconAlt, $username, $qb)
    {
        return   $qb->from('JCLEMemoBundle:Note', 'n')
                    ->Join('n.icon','i')
                    ->Join('n.createur','u')
                    ->where('i.alt = :altIcon')
                    ->setParameter('altIcon', $iconAlt )
                    ->andWhere('u.username = :username')           
                    ->setParameter('username', $username );
    }
    
}
