parameters:
#    sdz_user.example.class: SDZ\UserBundle\Example

#services:
#    sdz_user.example:
#        class: %sdz_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
